apply plugin: 'com.android.library'
apply plugin: 'ivy-publish'
apply from: 'build-common.gradle'
apply from: rootProject.file("versions.gradle")

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

android {

	defaultConfig {
		minSdkVersion osmand_minSdk
	}

	lintOptions {
		tasks.lint.enabled = false
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		aidl true
	}

	sourceSets {
		main {
			manifest.srcFile "AndroidManifest-library.xml"
			java.srcDirs = ["src", "src-gms", "src-google"]
		}
	}

	productFlavors {
		// CoreVersion
		// Build that doesn't include 3D OpenGL
		legacy {
			dimension "coreversion"
			resValue "string", "app_edition", ""
		}
	}

}

androidComponents {
    onVariants(selector().all()) { variant ->
        def taskName = variant.name.capitalize()
        
        tasks.matching { it.name == "package${taskName}Assets" }.configureEach {
            it.dependsOn(copyProjDb)
            it.dependsOn(collectFonts)
            it.dependsOn(copyPoiCategories)
            it.dependsOn(copyRouteActivities)
            it.dependsOn(copyColorPalettes)
            it.dependsOn(copyBundledAssets)
            it.dependsOn(copy3DModels)
            it.dependsOn(collectVoiceAssets)
            it.dependsOn(downloadStarsDb)
            it.dependsOn(downloadWorldMiniBasemap)
        }
        
        tasks.matching { it.name == "map${taskName}SourceSetPaths" }.configureEach {
            it.dependsOn(copyIcons)
        }
        
        tasks.matching { it.name == "package${taskName}Resources" }.configureEach {
            it.dependsOn(copyIcons)
        }
        
        tasks.matching { it.name == "generate${taskName}Resources" }.configureEach {
            it.dependsOn(copyIcons)
        }
        
        tasks.matching { it.name == "process${taskName}NavigationResources" }.configureEach {
            it.dependsOn(copyIcons)
        }

        tasks.matching { it.name == "compile${taskName}JavaWithJavac" }.configureEach {
            it.dependsOn collectExternalResources, buildOsmAndCore, cleanupDuplicatesInCore
        }
    }
}

version = System.getenv("OSMAND_BINARIES_IVY_REVISION") ?: "master-snapshot"
project.afterEvaluate {
	publishing {
		repositories {
			ivy {
				url = System.getenv("OSMAND_BINARIES_IVY_ROOT") ?: "./"
			}
		}
		publications {
			aar(IvyPublication) {
				artifact bundleLegacyFatDebugAar {
					archiveClassifier = 'debug'
				}
				artifact bundleLegacyFatReleaseAar {
					archiveClassifier = 'release'
				}
			}
		}
	}
}

dependencies {
	implementation 'com.google.android.gms:play-services-location:21.3.0'
}
