name: Remote Marine Compiler

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code with Submodules
      uses: actions/checkout@v4
      with:
        # Crucial for OsmAnd: Forces the server to download all asset submodules recursively
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Java Development Kit
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
