name: Remote Marine Compiler

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Source Code with Submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        path: android # Places your code in a folder named 'android'

    - name: Checkout OsmAnd Resources
      uses: actions/checkout@v4
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources # Places the icons right next to it, where Gradle expects them

    - name: Set up Java Development Kit
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Grant Execute Permission for Gradle
      working-directory: ./android
      run: chmod +x gradlew

    - name: Create local.properties
      run: |
        echo "sdk.dir=/home/administrator/Android/Sdk" > android/local.properties

    - name: Execute Cloud Compilation
      working-directory: ./android
      env:
        _JAVA_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.workers.max=2"
      run: ./gradlew clean :OsmAnd:assembleAndroidFullLegacyArm64Debug -x test --no-daemon

    - name: Upload Finished Installer APK
      uses: actions/upload-artifact@v4
      with:
        name: Nautical-OsmAnd-Installer
        # Updated path to look inside the new 'android' folder
        path: android/OsmAnd/build/outputs/apk/**/*.apk
